[project]
name = "beezzaants"
version = "0.1.0"
description = "An open-source swarm of buzzing bots and crawling code, powered by pizza, FocoosAI, Z-Ant, and Arduinos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
